Vagrant.configure("2") do |config|
  # Usa una imagen ligera de Ubuntu 22.04
  config.vm.box = "bento/ubuntu-22.04"

  # Configuración de red (accesible via IP)
  config.vm.network "private_network", ip: "192.168.33.20"

  config.vm.provider "virtualbox" do |vb|
    # Configuración de la memoria y núcleos del procesador
    vb.memory = "2048"  # 2 GB de RAM
    vb.cpus = 2         # 2 núcleos de CPU
  end
    # Configuracion de sincronizacion de carpetas
  config.vm.synced_folder ".", "/vagrant"

    #Dar privilegios sudo para ejecutar el script
  config.vm.provision "instalar_docker", type: "shell", path: "scripts/instalar_docker.sh", privileged: true
end